### PR TITLE
Update skills round css

### PR DESCRIPTION
**Pull request by zzhikai**
Rearranged labels, change colour of background and text.
Screenshot 2022-03-21 at 11 37 58 PM

Lowered brightness of colours of labels and changes from black background in label to `#1d1d1d`
Screenshot 2022-03-25 at 2 24 51 AM
 #93

### CODE REVIEW

**Comment by RyanCheungJF** [comment]
Tested on my local machine and the font sizing looks a bit different. Running Windows 10. I'll give it another look later.
Otherwise, the code looks okay. LMK if this is intended.

image

**Review by RyanCheungJF — COMMENTED** [review]
Tested on my local machine and the font sizing looks a bit different. Running Windows 10. I'll give it another look later.
Otherwise, the code looks okay. LMK if this is intended.

image

**Comment by zzhikai** [comment]
Yeap the font size is as intended, skills smaller than round of job application, could you ss again, i changed the font thickness, i think it only renders in windows.

**Comment by RyanCheungJF** [comment]
> @RyanCheungJF Yeap the font size is as intended, skills smaller than round of job application, could you ss again, i changed the font thickness, i think it only renders in windows.
> 
> Upon second inspection, I think I will make it the same font size to match our mock UI

image

I've pulled the latest changes from your branch. This is the latest result.

**Review by ryantanlien — APPROVED** [review]
LGTM! The colors are definitely less bright now and easier on the eyes

**Pull request merged**
